# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\Infrastructure\Http\Controller\GenerateLiveKitController:
        arguments:
            $livekitApiKey: '%env(LIVEKIT_API_KEY)%'
            $livekitApiSecret: '%env(LIVEKIT_API_SECRET)%'
            $livekitUrl: '%env(LIVEKIT_URL)%'


    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Application\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Shared\Domain\Event\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\Infrastructure\Security\RefreshTokenService:
        arguments:
            $ttl: 2592000 # 30 jours

    App\Infrastructure\Security\JWTLoginSuccessHandler:
        arguments:
            $refreshTokenService: '@App\Infrastructure\Security\RefreshTokenService'
            $cookieProviders: []


    App\Infrastructure\Http\Controller\UsersGetJwtTokenFromFirebaseAuthAction:
        arguments:
            $queryBus: '@App\Shared\Infrastructure\Bus\QueryBus'
            $refreshTokenService: '@App\Infrastructure\Security\RefreshTokenService'
            $userRepository: '@App\Infrastructure\Persistence\Doctrine\Repository\UserRepository'
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
