security:
#    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
#    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
#
#    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
#    providers:
#        users_in_memory: { memory: null }


    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Infrastructure\Persistence\Doctrine\Entity\UserEntity:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Infrastructure\Security\UserProvider


#    firewalls:
#        dev:
#            # Ensure dev tools and static assets are always allowed
#            pattern: ^/(_profiler|_wdt|assets|build)/
#            security: false
#        main:
#            lazy: true
#            provider: users_in_memory
#
#            # Activate different ways to authenticate:
#            # https://symfony.com/doc/current/security.html#the-firewall
#
#            # https://symfony.com/doc/current/security/impersonating_user.html
#            # switch_user: true


    firewalls:

        refresh:
            pattern: ^/api/auth/refresh
            stateless: true
            custom_authenticators:
                - App\Infrastructure\Security\RefreshTokenAuthenticator
            provider: app_user_provider

        api_doc:
            pattern: ^/api/doc
            stateless: true
            # pas de jwt ici

        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                #                success_handler: lexik_jwt_authentication.handler.authentication_success
                success_handler: App\Infrastructure\Security\JWTLoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: app_user_provider

        api_public:
            pattern: ^/api/photo
            stateless: true
            security: false  # Pas d'authentification requise

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider


    # Note: Only the *first* matching rule is applied
#    access_control:
#        # - { path: ^/admin, roles: ROLE_ADMIN }
#        # - { path: ^/profile, roles: ROLE_USER }

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/generate-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/jwt-by-firebase-token, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: ROLE_USER }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
