services:

  nginx_api:
    image: nginx:1.23-alpine
    volumes:
      - ../symfony-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    networks:
      - drinkks-net

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LIVEKIT_URL_WSS: ${LIVEKIT_URL_WSS}
      LIVEKIT_URL_HTTP: ${LIVEKIT_URL_HTTP}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ../symfony-app:/var/www/html
      - ../app/lib:/var/www/html/flutter_lib
    depends_on:
      - mysql
    networks:
      - drinkks-net

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
#      - database_data:/var/lib/mysql
        #      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
        - ${MYSQL_DATA_DIR}:/var/lib/mysql
        - ${MYSQL_LOG_DIR}:/var/log/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - drinkks-net

  phpmyadmin:
    image: phpmyadmin:5.2.0
    #    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${PMA_PORT}:80
    networks:
      - drinkks-net

#volumes:
#  database_data:

networks:
  drinkks-net:
    external: true
